my:
    resource: "@MyBundle/Resources/config/routing.yml"
    prefix:   /

path_bundle:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
