login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }

login_check:
    path: /login_check

login_out:
    path: /logout

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_add_tag:
    path:     /tags/add
    defaults: { _controller: BlogBundle:Tag:add }
