test_index:
  path: /tests/{lang}/{name}/{page}
  defaults: {_controller: AppBundle:Test:index, name:Pepe, page:1}
  methods: [GET, POST]
  requirements:
    name: "[a-zA-Z]*"
    page: \d+
    lang: es|en|fr

test_create:
  path: /tests/create
  defaults: {_controller: AppBundle:Test:create}

test_read:
  path: /tests/read
  defaults: {_controller: AppBundle:Test:read}

test_update:
  path: /tests/update/{id}/{titulo}/{descripcion}/{precio}
  defaults: {_controller: AppBundle:Test:update}

test_delete:
  path: /tests/delete/{id}
  defaults: {_controller: AppBundle:Test:delete}

test_native:
  path: /tests/native
  defaults: {_controller: AppBundle:Test:nativeSql}

test_form:
  path: /tests/form
  defaults: { _controller: AppBundle:Test:form}

test_validateEmail:
  path: /tests/validate-email/{email}
  defaults: { _controller: AppBundle:Test:validateEmail}
